# site info

#  language codes https://www.w3schools.com/tags/ref_language_codes.asp
# territory codes https://www.w3schools.com/tags/ref_country_codes.asp

lang: zh-Hans # default language tag of the site. 
locale: zh_CN # og:locale of the format language_TERRITORY.
author: "your name" # name of site's author
title: less style, please! # name of the site
description: > # description of the site (multiple lines allowed)
  Write an awesome description for your new site here. You can edit
  this line in _config.yml. It will appear in your document head meta
  (for Google search results) and in your feed.xml site description.
url: https://feeshy.github.io # the base hostname & protocol for your site
baseurl: "/less-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
# webmaster_verifications: # verify ownership with several search services
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

# favicon & app icon

# generate modern svg favicon at https://realfavicongenerator.net/svg-favicon/
# generate png icons pack at https://realfavicongenerator.net/
# generate maskable chrome icons at https://maskable.app/editor/

favicon:
  ico: "/favicon.ico" # legacy 'favicon.ico' at the root folder of your site, it is highly recommended not changing this name
  svg: "/favicon.svg" # name+extension of modern vector favicon
  ios: "/maskable-180x180.png" # icon for Safari
ms_tile_color: "#da532c" # hex background for windows 8.1~10 tile
webmanifest: "/site.webmanifest" # icon config file path for Chrome

# pwa

pwa:
  enabled: false # set false to temporarily disable this plugin
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 0 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "assets/background/*.{png,svg,gif}"
    - "assets/css/*.{css}"
    - "assets/js/*.{js}"
    - "assets/OpenFont/**/*.{eot,ttf,woff,woff2}"
  precache_glob_ignores: # Optional
    - index.html

# theme config

theme: less-style-please # if you use it as a local theme
# remote_theme: feeshy/less-style-please # if you use it as a remote theme on github

show_logo: false # show the svg favicon in home page and archive page
show_description: false # show blog description in home page
sort_by_modified_date: false # sort posts by modified date rather than published date. Attention: You will have to set last_modified_date for every post
tags_page:
  enabled: true # creates a query page for all posts with specific tags
  url: archive # permalink for your tags page
chinese_webfonts: true # by disabling this, page loading speed will be increased significantly
# background_image: # path to background images for light and dark mode
#   light: ""
#   dark: ""
nav:
  back_home: "home" # customize text for homepage link
  go_to_top: "🔝" # customize text for go to top button
date_format: "%Y-%m-%d" # customize how date is formatted at https://strftime.net/
copyright: "by" # available values: "all-rights-reserved", "by-nc-nd", "by-nd", "by-nc-sa", "by-nc", "by-sa", "by", "public-domain". choose here https://chooser-beta.creativecommons.org/
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# defaults

permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: "*/index.md"
      type: pages
    values:
      layout: archive
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  -
    scope:
      path: literature
      type: posts
    values:
      fonts: serif # this activates an alternative set of serif typefaces
      dropcap: true # this activates a drop cap effect

# build settings

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "highlight", "footnotes", "with_toc_data"]
toc:
  min_level: 2 # value: 1-6
  max_level: 3 # value: 1-6
sass:
  sass_dir: _sass
  style: compressed
feed:
  posts_limit: 10 # max number of posts on feed

# plugins

plugins:
  # - jekyll-remote-theme # enable this if you use it as a remote theme
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc
  - jekyll-pwa-workbox
  - jekyll-redirect-from